# Generated by Django 3.1.6 on 2021-02-23 16:27

from django.db import migrations, models
import django.db.models.deletion
import my_site.restful.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("total_count", my_site.restful.models.APICounterField(default=0)),
                ("last_add_by", models.SmallIntegerField(default=0)),
                ("last_modified_by", models.GenericIPAddressField(default="172.0.0.1")),
                ("last_modified_from", models.URLField(default="http://localhost/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("add_by", models.SmallIntegerField(default=0)),
                ("modified_by", models.GenericIPAddressField(default="172.0.0.1")),
                ("modified_from", models.URLField(default="http://localhost/")),
                (
                    "like",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="my_app.like",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
