[host]
user = "<Host `user`>"
password = "<Host `password`>"

[django]
secret-key = "<Django `SECRET_KEY`>"

[mysql]
user = "<MySQL `USER`>"
password = "<MySQL `PASSWORD`>"

[tencent-cloud]
app-id = "<Tencent Cloud `APPID`>"
access.id = "<Tencent Cloud `SecretID`>"
access.key = "<Tencent Cloud `SecretKey`>"

[aliyun]
role-arn = "<Aliyun `Role ARN`>"
access.id = "<Aliyun `AccessKey ID`>"
access.key = "<Aliyun `AccessKey Secret`>"
