"""
Django settings for mysite project in BASE mode.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""


from mysite.settings import *


DEBUG = False

ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "myapp",
]

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

# STATIC_URL = "./static/"
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# MEDIA_URL = "./media/"
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

AUTH_USER_MODEL = "myapp.MyUser"
